// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Errors$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Errors",
  "sourceName": "contracts/Constants.sol",
  "abi": [
    {
      "inputs": [],
      "name": "DeploymentFailed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "Misconfigured",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "MissingPayment",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "NotInCohort",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "SecretMismatch",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "SignerMismatch",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "UnableToService",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "ZeroSecret",
      "type": "error"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Errors",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Errors$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/Constants.sol:Errors",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Errors$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Errors",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Errors$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/Constants.sol:Errors",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Errors$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Errors",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Errors$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/Constants.sol:Errors",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Errors$Type["abi"]>>;
}
