// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Consumer$Type } from "./Consumer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Consumer"]: Consumer$Type;
    ["contracts/Consumer.sol:Consumer"]: Consumer$Type;
  }

  interface ContractTypesMap {
    ["Consumer"]: GetContractReturnType<Consumer$Type["abi"]>;
    ["contracts/Consumer.sol:Consumer"]: GetContractReturnType<Consumer$Type["abi"]>;
  }
}
