// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SSTORE2$Type } from "./SSTORE2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SSTORE2"]: SSTORE2$Type;
    ["solady/src/utils/SSTORE2.sol:SSTORE2"]: SSTORE2$Type;
  }

  interface ContractTypesMap {
    ["SSTORE2"]: GetContractReturnType<SSTORE2$Type["abi"]>;
    ["solady/src/utils/SSTORE2.sol:SSTORE2"]: GetContractReturnType<SSTORE2$Type["abi"]>;
  }
}
