// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface LibPRNG$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "LibPRNG",
  "sourceName": "solady/src/utils/LibPRNG.sol",
  "abi": [
    {
      "inputs": [],
      "name": "InvalidInitialLazyShufflerLength",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "InvalidNewLazyShufflerLength",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "LazyShuffleFinished",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "LazyShufflerAlreadyInitialized",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "LazyShufflerGetOutOfBounds",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "LazyShufflerNotInitialized",
      "type": "error"
    }
  ],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220717935ebfe63c002600b4293f6d2e5654a4c4fb93aa87279b7095db6396de3b464736f6c63430008190033",
  "deployedBytecode": "0x5f80fdfea2646970667358221220717935ebfe63c002600b4293f6d2e5654a4c4fb93aa87279b7095db6396de3b464736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "LibPRNG",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibPRNG$Type["abi"]>>;
  export function deployContract(
    contractName: "solady/src/utils/LibPRNG.sol:LibPRNG",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibPRNG$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "LibPRNG",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibPRNG$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "solady/src/utils/LibPRNG.sol:LibPRNG",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibPRNG$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "LibPRNG",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibPRNG$Type["abi"]>>;
  export function getContractAt(
    contractName: "solady/src/utils/LibPRNG.sol:LibPRNG",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibPRNG$Type["abi"]>>;
}
