services:
  gibrandom-indexer-postgres:
    container_name: gibrandom-indexer-postgres
    image: gibsfinance/postgres
    shm_size: 16g
    platform: linux/amd64
    command: ['postgres']
    ports:
      - 9151:5432
    volumes:
      - ./packages/indexer/postgres-data:/var/lib/postgresql/data
    networks:
      - gibrandom
    environment:
      - POSTGRES_DB=gibrandom-indexer
      - POSTGRES_USER=gibrandom-indexer
      - POSTGRES_PASSWORD=password

  gibrandom-provider-postgres:
    container_name: gibrandom-provider-postgres
    image: gibsfinance/postgres
    shm_size: 16g
    platform: linux/amd64
    command: ['postgres']
    ports:
      - 9182:5432
    volumes:
      - ./packages/provider/postgres-data:/var/lib/postgresql/data
    networks:
      - gibrandom
    environment:
      - POSTGRES_DB=gibrandom
      - POSTGRES_USER=gibrandom
      - POSTGRES_PASSWORD=password

  gibrandom-indexer:
    container_name: gibrandom-indexer
    shm_size: 16g
    command: bash -c "pnpm run build && pnpm dev"
    build:
      context: ./packages/indexer
    ports:
      - 42069:42069
    networks:
      - gibrandom
    depends_on:
      - gibrandom-indexer-postgres
    volumes:
      - ./packages/indexer/postgres-data:/app/postgres-data
      - ./packages/indexer/generated:/app/generated
      - ./packages/indexer/src:/app/src
      - ./packages/indexer/.eslintrc.json:/app/.eslintrc.json
      - ./packages/indexer/pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./packages/indexer/ponder-env.d.ts:/app/ponder-env.d.ts
      - ./packages/indexer/ponder.config.ts:/app/ponder.config.ts
      - ./packages/indexer/ponder.schema.ts:/app/ponder.schema.ts
      - ./packages/indexer/tsconfig.json:/app/tsconfig.json
    environment:
      DATABASE_URL: postgres://gibrandom-indexer:password@gibrandom-indexer-postgres:5432/gibrandom-indexer
      NETWORK: "${NETWORK:-pulsechainV4}"
      HOST: '0.0.0.0'

  gibrandom-provider:
    container_name: gibrandom-provider
    shm_size: 16g
    command: >
      bash -c "
        echo 'Waiting for 1 minute before starting the provider...'
        sleep 60
        echo 'Starting consumer now'
        bun run provide:dev
      "
    build:
      context: ./packages/provider
    networks:
      - gibrandom
    depends_on:
      - gibrandom-indexer
      - gibrandom-provider-postgres
    volumes:
      - ./packages/provider/postgres-data:/app/postgres-data
      - ./packages/provider/src:/app/src
      - ./packages/provider/codegen.config.cjs:/app/codegen.config.cjs
      - ./packages/provider/config.ts:/app/config.ts
      - ./packages/provider/knexfile.ts:/app/knexfile.ts
      - ./packages/provider/package.json:/app/package.json
      - ./packages/provider/pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./packages/provider/tsconfig.json:/app/tsconfig.json
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://gibrandom:password@gibrandom-provider-postgres:5432/gibrandom
      DEBUG: '${DEBUG:-💬}'
      INDEXER_URL: http://gibrandom-indexer:42069
      MNEMONIC: $MNEMONIC
      RANDOMNESS_MNEMONIC: $RANDOMNESS_MNEMONIC
      CHAIN_ID: 943

  gibrandom-consume:
    container_name: gibrandom-consume
    shm_size: 16g
    command: >
      bash -c "
        echo 'Waiting for 1 minute before starting the consumer...'
        sleep 60
        echo 'Starting consumer now'
        bun run consumer-bot
      "
    build:
      context: ./packages/provider
    networks:
      - gibrandom
    depends_on:
      - gibrandom-indexer
      - gibrandom-provider-postgres
    volumes:
      - ./packages/provider/postgres-data:/app/postgres-data
      - ./packages/provider/src:/app/src
      - ./packages/provider/codegen.config.cjs:/app/codegen.config.cjs
      - ./packages/provider/config.ts:/app/config.ts
      - ./packages/provider/knexfile.ts:/app/knexfile.ts
      - ./packages/provider/package.json:/app/package.json
      - ./packages/provider/pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./packages/provider/tsconfig.json:/app/tsconfig.json
    env_file:
      - .env
    environment:
      DEBUG: '${DEBUG:-💬}'
      INDEXER_URL: http://gibrandom-indexer:42069
      MNEMONIC: $MNEMONIC
      RANDOMNESS_MNEMONIC: $RANDOMNESS_MNEMONIC
      CHAIN_ID: 943

networks:
  gibrandom:
    name: gibrandom
    driver: bridge

volumes:
  gibrandom:
    external: true