// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface PreimageLocation$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "PreimageLocation",
  "sourceName": "contracts/PreimageLocation.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212204f2084296b93b4edf4ae253420347c9fdf2246220d5451a1090cce9de1b3d94864736f6c63430008190033",
  "deployedBytecode": "0x5f80fdfea26469706673582212204f2084296b93b4edf4ae253420347c9fdf2246220d5451a1090cce9de1b3d94864736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "PreimageLocation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<PreimageLocation$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/PreimageLocation.sol:PreimageLocation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<PreimageLocation$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "PreimageLocation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<PreimageLocation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/PreimageLocation.sol:PreimageLocation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<PreimageLocation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "PreimageLocation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<PreimageLocation$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/PreimageLocation.sol:PreimageLocation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<PreimageLocation$Type["abi"]>>;
}
