// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Random$Type } from "./Random";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Random"]: Random$Type;
    ["contracts/Random.sol:Random"]: Random$Type;
  }

  interface ContractTypesMap {
    ["Random"]: GetContractReturnType<Random$Type["abi"]>;
    ["contracts/Random.sol:Random"]: GetContractReturnType<Random$Type["abi"]>;
  }
}
