// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Etcher$Type } from "./Etcher";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Etcher"]: Etcher$Type;
    ["contracts/test/Etcher.sol:Etcher"]: Etcher$Type;
  }

  interface ContractTypesMap {
    ["Etcher"]: GetContractReturnType<Etcher$Type["abi"]>;
    ["contracts/test/Etcher.sol:Etcher"]: GetContractReturnType<Etcher$Type["abi"]>;
  }
}
