// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { LibMulticaller$Type } from "./LibMulticaller";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LibMulticaller"]: LibMulticaller$Type;
    ["multicaller/src/LibMulticaller.sol:LibMulticaller"]: LibMulticaller$Type;
  }

  interface ContractTypesMap {
    ["LibMulticaller"]: GetContractReturnType<LibMulticaller$Type["abi"]>;
    ["multicaller/src/LibMulticaller.sol:LibMulticaller"]: GetContractReturnType<LibMulticaller$Type["abi"]>;
  }
}
