// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface LibMulticaller$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "LibMulticaller",
  "sourceName": "multicaller/src/LibMulticaller.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220d43eff2834d0070c9088976efa8eea5c4b8839164137b893fb2b3a8e1e15b68a64736f6c63430008190033",
  "deployedBytecode": "0x5f80fdfea2646970667358221220d43eff2834d0070c9088976efa8eea5c4b8839164137b893fb2b3a8e1e15b68a64736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "LibMulticaller",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibMulticaller$Type["abi"]>>;
  export function deployContract(
    contractName: "multicaller/src/LibMulticaller.sol:LibMulticaller",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibMulticaller$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "LibMulticaller",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibMulticaller$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "multicaller/src/LibMulticaller.sol:LibMulticaller",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibMulticaller$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "LibMulticaller",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibMulticaller$Type["abi"]>>;
  export function getContractAt(
    contractName: "multicaller/src/LibMulticaller.sol:LibMulticaller",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibMulticaller$Type["abi"]>>;
}
