// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MulticallerWithSender$Type } from "./MulticallerWithSender";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MulticallerWithSender"]: MulticallerWithSender$Type;
    ["multicaller/src/MulticallerWithSender.sol:MulticallerWithSender"]: MulticallerWithSender$Type;
  }

  interface ContractTypesMap {
    ["MulticallerWithSender"]: GetContractReturnType<MulticallerWithSender$Type["abi"]>;
    ["multicaller/src/MulticallerWithSender.sol:MulticallerWithSender"]: GetContractReturnType<MulticallerWithSender$Type["abi"]>;
  }
}
