// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MulticallerWithSigner$Type } from "./MulticallerWithSigner";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MulticallerWithSigner"]: MulticallerWithSigner$Type;
    ["multicaller/src/MulticallerWithSigner.sol:MulticallerWithSigner"]: MulticallerWithSigner$Type;
  }

  interface ContractTypesMap {
    ["MulticallerWithSigner"]: GetContractReturnType<MulticallerWithSigner$Type["abi"]>;
    ["multicaller/src/MulticallerWithSigner.sol:MulticallerWithSigner"]: GetContractReturnType<MulticallerWithSigner$Type["abi"]>;
  }
}
