// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Multicaller$Type } from "./Multicaller";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Multicaller"]: Multicaller$Type;
    ["multicaller/src/Multicaller.sol:Multicaller"]: Multicaller$Type;
  }

  interface ContractTypesMap {
    ["Multicaller"]: GetContractReturnType<Multicaller$Type["abi"]>;
    ["multicaller/src/Multicaller.sol:Multicaller"]: GetContractReturnType<Multicaller$Type["abi"]>;
  }
}
