// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { StorageSlot$Type } from "./StorageSlot";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StorageSlot"]: StorageSlot$Type;
    ["contracts/StorageSlot.sol:StorageSlot"]: StorageSlot$Type;
  }

  interface ContractTypesMap {
    ["StorageSlot"]: GetContractReturnType<StorageSlot$Type["abi"]>;
    ["contracts/StorageSlot.sol:StorageSlot"]: GetContractReturnType<StorageSlot$Type["abi"]>;
  }
}
