// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SlotDerivation$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SlotDerivation",
  "sourceName": "contracts/SlotDerivation.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212207fdd9ff2cdd1c6a1cac4ddf7fcff4ea1d46faf6739957296982fdd51b53f3d3164736f6c63430008190033",
  "deployedBytecode": "0x5f80fdfea26469706673582212207fdd9ff2cdd1c6a1cac4ddf7fcff4ea1d46faf6739957296982fdd51b53f3d3164736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SlotDerivation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/SlotDerivation.sol:SlotDerivation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SlotDerivation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SlotDerivation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/SlotDerivation.sol:SlotDerivation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SlotDerivation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SlotDerivation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/SlotDerivation.sol:SlotDerivation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
}
