// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { LibBitmap$Type } from "./LibBitmap";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LibBitmap"]: LibBitmap$Type;
    ["solady/src/utils/LibBitmap.sol:LibBitmap"]: LibBitmap$Type;
  }

  interface ContractTypesMap {
    ["LibBitmap"]: GetContractReturnType<LibBitmap$Type["abi"]>;
    ["solady/src/utils/LibBitmap.sol:LibBitmap"]: GetContractReturnType<LibBitmap$Type["abi"]>;
  }
}
