// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface LibBitmap$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "LibBitmap",
  "sourceName": "solady/src/utils/LibBitmap.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220ff9bc94e1489417d376af13ab27914fa346dbdce023b1783028c53a426c6f2ae64736f6c63430008190033",
  "deployedBytecode": "0x5f80fdfea2646970667358221220ff9bc94e1489417d376af13ab27914fa346dbdce023b1783028c53a426c6f2ae64736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "LibBitmap",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibBitmap$Type["abi"]>>;
  export function deployContract(
    contractName: "solady/src/utils/LibBitmap.sol:LibBitmap",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibBitmap$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "LibBitmap",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibBitmap$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "solady/src/utils/LibBitmap.sol:LibBitmap",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibBitmap$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "LibBitmap",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibBitmap$Type["abi"]>>;
  export function getContractAt(
    contractName: "solady/src/utils/LibBitmap.sol:LibBitmap",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibBitmap$Type["abi"]>>;
}
