// M3 generator for the ZK-Wordle SETTLEMENT circuit (wordle_solve): exports the on-chain Groth16
// verifier AND the matching proof fixture from ONE zkey, in a single pass.
//
// THE RULE THAT KEEPS THIS SAFE (same as genProofFixtures.ts): the committed verifier .sol and the
// committed fixture JSON must come from the SAME zkey. This script exports the Solidity verifier from
// build/wordle_solve/wordle_solve_final.zkey and then writes the fixture proved against that same
// zkey — so run it as a UNIT after any circuit/setup change; never regenerate one artifact alone.
//
// Trusted setup: wordle_solve is ~4.4k constraints, so a power-13 dev ptau (fixed public beacon, see
// harness.ts) is generated locally — small enough that it does NOT risk the OOM that large local ptau
// generation caused on M1 (the sudoku power-15 ptau is downloaded, not generated). DEV/TEST ONLY —
// a real per-circuit ceremony is still required before any production deployment.
//
// Run: cd examples/games/zk-skill && npx tsx scripts/genWordleSolve.ts
// (or: pnpm --filter @gibs/zk-skill gen:wordle-solve)

import { execFileSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { setupCircuit, prove, verify, PACKAGE_ROOT, BUILD_DIR, NODE_MODULES_DIR } from '../src/harness.js'
import { wordToIndices } from '../src/wordle.js'
import { buildDictTree, buildWordleSolveWitnessInput, TEST_DICTIONARY } from '../src/wordleSolve.js'

const PTAU_POWER = 13 // 2^13 = 8192 >= wordle_solve constraints (~4.4k)
const REPO_ROOT = path.resolve(PACKAGE_ROOT, '../../..')
const FIXTURES_DIR = path.join(REPO_ROOT, 'packages/contracts/test/foundry/fixtures')
const VERIFIER_OUT = path.join(
  REPO_ROOT,
  'packages/contracts/contracts/zk/generated/WordleSolveVerifier.sol',
)

const GENERATED_HEADER = `// SPDX-License-Identifier: GPL-3.0
// GENERATED FILE — DO NOT EDIT BY HAND.
// Source: examples/games/zk-skill/circuits/wordle_solve.circom (circom -> snarkjs 0.7.6 groth16).
// Regenerate: cd examples/games/zk-skill && npx tsx scripts/genWordleSolve.ts
// (or: pnpm --filter @gibs/zk-skill gen:wordle-solve)
// DEV/TEST trusted setup (fixed power-13 beacon ptau + fixed contribution entropy) -- NOT for production.
`

function calldataFromProof(proof: any, publicSignals: string[]) {
  return {
    pA: [proof.pi_a[0], proof.pi_a[1]] as [string, string],
    pB0: [proof.pi_b[0][1], proof.pi_b[0][0]] as [string, string],
    pB1: [proof.pi_b[1][1], proof.pi_b[1][0]] as [string, string],
    pC: [proof.pi_c[0], proof.pi_c[1]] as [string, string],
    pubSignals: publicSignals,
  }
}

function exportVerifier(zkeyPath: string) {
  const bin = path.join(NODE_MODULES_DIR, '.bin', 'snarkjs')
  const raw = path.join(BUILD_DIR, 'wordle_solve', 'WordleSolveVerifier.raw.sol')
  execFileSync(bin, ['zkey', 'export', 'solidityverifier', zkeyPath, raw], { stdio: 'pipe' })
  let sol = readFileSync(raw, 'utf8')
  // snarkjs emits `contract Groth16Verifier` + its own SPDX/pragma preamble; rename the contract and
  // prepend our generated-file header (drop snarkjs's leading SPDX line to avoid a duplicate).
  sol = sol.replace(/contract\s+Groth16Verifier\b/, 'contract WordleSolveVerifier')
  sol = sol.replace(/^\/\/ SPDX-License-Identifier:[^\n]*\n/, '')
  writeFileSync(VERIFIER_OUT, GENERATED_HEADER + sol)
  console.log(`[gen] wrote ${VERIFIER_OUT}`) // eslint-disable-line no-console
}

async function main() {
  console.log('[gen] wordle_solve: compile + power-13 dev setup...') // eslint-disable-line no-console
  const setup = setupCircuit('wordle_solve', PTAU_POWER)
  exportVerifier(setup.zkeyPath)

  // Fixture vector: word="crane"; committed 6-guess sequence solves at guess #2 → guesses-used=2 (3.50×).
  const dict = await buildDictTree([...TEST_DICTIONARY])
  const word = wordToIndices('crane')
  const salt = 424242n
  const guesses = ['slate', 'crane', 'ghost', 'dozen', 'jumbo', 'unfit'].map(wordToIndices)

  const input = await buildWordleSolveWitnessInput({ word, salt, guesses, dict })
  const { proof, publicSignals } = await prove(setup, input)
  const ok = await verify(setup, publicSignals, proof)
  if (!ok) throw new Error('genWordleSolve: proof failed in-process verify — aborting')
  if (publicSignals.length !== 4) {
    throw new Error(`genWordleSolve: expected 4 public signals, got ${publicSignals.length}`)
  }
  if (input.guessesUsed !== '2') throw new Error('genWordleSolve: fixture should solve at guess 2')

  mkdirSync(FIXTURES_DIR, { recursive: true })
  const outPath = path.join(FIXTURES_DIR, 'wordleSolveProof.json')
  writeFileSync(
    outPath,
    JSON.stringify(
      {
        _comment:
          'GENERATED by examples/games/zk-skill/scripts/genWordleSolve.ts. A real Groth16 proof for ' +
          'the ALL-GREEN solve vector word="crane", committed guesses [slate,crane,ghost,dozen,jumbo,' +
          'unfit] (first all-green at guess #2 → guessesUsed=2 → 3.50x). Proved with the SAME ' +
          'build/wordle_solve/wordle_solve_final.zkey the committed WordleSolveVerifier.sol was ' +
          'exported from. publicSignals / packed pub[] order is [commit, guessesCommit, dictRoot, ' +
          'guessesUsed] (4 signals), matching circuits/wordle_solve.circom `component main`. pA/pB/pC ' +
          'are already in calldata form (pB rows swapped) as WordleSolveVerifier.verifyProof expects.',
        vector: {
          word,
          guesses,
          salt: input.salt,
          commit: input.commit,
          guessesCommit: input.guessesCommit,
          dictRoot: input.dictRoot,
          guessesUsed: input.guessesUsed,
        },
        ...calldataFromProof(proof, publicSignals),
      },
      null,
      2,
    ) + '\n',
  )
  console.log(`[gen] wrote ${outPath}`) // eslint-disable-line no-console
  console.log('[gen] done.') // eslint-disable-line no-console
}

main().catch((e) => {
  console.error(e) // eslint-disable-line no-console
  process.exitCode = 1
})
