// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MulticallerEtcher$Type } from "./MulticallerEtcher";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MulticallerEtcher"]: MulticallerEtcher$Type;
    ["multicaller/src/MulticallerEtcher.sol:MulticallerEtcher"]: MulticallerEtcher$Type;
  }

  interface ContractTypesMap {
    ["MulticallerEtcher"]: GetContractReturnType<MulticallerEtcher$Type["abi"]>;
    ["multicaller/src/MulticallerEtcher.sol:MulticallerEtcher"]: GetContractReturnType<MulticallerEtcher$Type["abi"]>;
  }
}
