// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { FundedConsumer$Type } from "./FundedConsumer";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FundedConsumer"]: FundedConsumer$Type;
    ["contracts/FundedConsumer.sol:FundedConsumer"]: FundedConsumer$Type;
  }

  interface ContractTypesMap {
    ["FundedConsumer"]: GetContractReturnType<FundedConsumer$Type["abi"]>;
    ["contracts/FundedConsumer.sol:FundedConsumer"]: GetContractReturnType<FundedConsumer$Type["abi"]>;
  }
}
