// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { AbiParameterToPrimitiveType, GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface FundedConsumer$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "FundedConsumer",
  "sourceName": "contracts/FundedConsumer.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_consumer",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "_random",
          "type": "address"
        }
      ],
      "stateMutability": "payable",
      "type": "constructor"
    }
  ],
  "bytecode": "0x60c0601f6100d838819003918201601f19168301916001600160401b03831184841017607757808492604094855283398101031260735760476020604183608b565b9201608b565b6001600160a01b039182166080521660a0526040516039908161009f823960805181505060a051815050f35b5f80fd5b634e487b7160e01b5f52604160045260245ffd5b51906001600160a01b038216820360735756fe5f80fdfea2646970667358221220059c354d7fff80649aeed1890122242cd3270aa40bea3cebaad422f4bb72179e64736f6c63430008190033",
  "deployedBytecode": "0x5f80fdfea2646970667358221220059c354d7fff80649aeed1890122242cd3270aa40bea3cebaad422f4bb72179e64736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "FundedConsumer",
    constructorArgs: [_consumer: AbiParameterToPrimitiveType<{"name":"_consumer","type":"address"}>, _random: AbiParameterToPrimitiveType<{"name":"_random","type":"address"}>],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<FundedConsumer$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/FundedConsumer.sol:FundedConsumer",
    constructorArgs: [_consumer: AbiParameterToPrimitiveType<{"name":"_consumer","type":"address"}>, _random: AbiParameterToPrimitiveType<{"name":"_random","type":"address"}>],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<FundedConsumer$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "FundedConsumer",
    constructorArgs: [_consumer: AbiParameterToPrimitiveType<{"name":"_consumer","type":"address"}>, _random: AbiParameterToPrimitiveType<{"name":"_random","type":"address"}>],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<FundedConsumer$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/FundedConsumer.sol:FundedConsumer",
    constructorArgs: [_consumer: AbiParameterToPrimitiveType<{"name":"_consumer","type":"address"}>, _random: AbiParameterToPrimitiveType<{"name":"_random","type":"address"}>],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<FundedConsumer$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "FundedConsumer",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<FundedConsumer$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/FundedConsumer.sol:FundedConsumer",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<FundedConsumer$Type["abi"]>>;
}
