// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IRandom$Type } from "./IRandom";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IRandom"]: IRandom$Type;
    ["contracts/implementations/IRandom.sol:IRandom"]: IRandom$Type;
  }

  interface ContractTypesMap {
    ["IRandom"]: GetContractReturnType<IRandom$Type["abi"]>;
    ["contracts/implementations/IRandom.sol:IRandom"]: GetContractReturnType<IRandom$Type["abi"]>;
  }
}
