// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Reader$Type } from "./Reader";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Reader"]: Reader$Type;
    ["contracts/Reader.sol:Reader"]: Reader$Type;
  }

  interface ContractTypesMap {
    ["Reader"]: GetContractReturnType<Reader$Type["abi"]>;
    ["contracts/Reader.sol:Reader"]: GetContractReturnType<Reader$Type["abi"]>;
  }
}
