// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface EfficientHashLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "EfficientHashLib",
  "sourceName": "solady/src/utils/EfficientHashLib.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220ea9fc80ef693b4772a2ac9b9feb0d74a843ea21296a2794e82552df74313b9eb64736f6c63430008190033",
  "deployedBytecode": "0x5f80fdfea2646970667358221220ea9fc80ef693b4772a2ac9b9feb0d74a843ea21296a2794e82552df74313b9eb64736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "EfficientHashLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EfficientHashLib$Type["abi"]>>;
  export function deployContract(
    contractName: "solady/src/utils/EfficientHashLib.sol:EfficientHashLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EfficientHashLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "EfficientHashLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EfficientHashLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "solady/src/utils/EfficientHashLib.sol:EfficientHashLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EfficientHashLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "EfficientHashLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EfficientHashLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "solady/src/utils/EfficientHashLib.sol:EfficientHashLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EfficientHashLib$Type["abi"]>>;
}
