// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ConsumerReceiver$Type } from "./ConsumerReceiver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ConsumerReceiver"]: ConsumerReceiver$Type;
    ["contracts/implementations/ConsumerReceiver.sol:ConsumerReceiver"]: ConsumerReceiver$Type;
  }

  interface ContractTypesMap {
    ["ConsumerReceiver"]: GetContractReturnType<ConsumerReceiver$Type["abi"]>;
    ["contracts/implementations/ConsumerReceiver.sol:ConsumerReceiver"]: GetContractReturnType<ConsumerReceiver$Type["abi"]>;
  }
}
